.github/CODEOWNERS
=> ci: explicitly list users in codewoners

.github/workflows/tests.yaml, codecov.yaml, jarvis_sdk_node/package.json
=> ci: fix the codecov reporter setup

jarvis_sdk_node/src/examples/consent.ts, jarvis_sdk_node/src/examples/identity_ids.ts, jarvis_sdk_node/src/sdk/__test__/config.test.ts, jarvis_sdk_node/src/sdk/__test__/email_config.test.ts, jarvis_sdk_node/src/sdk/client/client.ts, jarvis_sdk_node/src/sdk/config.ts, jarvis_sdk_node/src/sdk/model/__test__/application_space.test.ts, jarvis_sdk_node/src/sdk/model/__test__/consent_challenge.test.ts, jarvis_sdk_node/src/sdk/model/__test__/customer.test.ts, jarvis_sdk_node/src/sdk/model/application_space.ts, jarvis_sdk_node/src/sdk/model/customer.ts
=> Add read customer and CRUD + list of app spaces methods

.github/workflows/release.yaml
=> ci: add missing install step

.github/workflows/release.yaml
=> ci: add the release frequency tracking

README.md
=> docs: fixing broken link to example config file

jarvis_sdk_node/src/sdk/__test__/identity.test.ts, jarvis_sdk_node/src/sdk/identity.ts, jarvis_sdk_node/src/sdk/model/__test__/invitation.test.ts, jarvis_sdk_node/src/sdk/model/__test__/property.test.ts, jarvis_sdk_node/src/sdk/model/invitation.ts, jarvis_sdk_node/src/sdk/model/property.ts, jarvis_sdk_node/src/sdk/utils/__test__/utils.test.ts, jarvis_sdk_node/src/sdk/utils/utils.ts
This PR brings new methods:
- `createEmailInvitation`
- `checkInvitationState`
- `resendInvitation`
- `cancelInvitation`
=> Support for email invitation

.github/CODEOWNERS
=> chore: add arxeiss as code owner

jarvis_sdk_node/src/index.ts
=> Expose config client type

.github/CODEOWNERS, .github/workflows/release-notes.yaml
this action requires user token so it triggers another
github action after creating githubrelease
=> ci: trigger the release pipeline after merging release PR

.github/workflows/release.yaml
=> ci: use deployed status for cu task

jarvis_sdk_node/README.md, jarvis_sdk_node/package-lock.json, jarvis_sdk_node/package.json, jarvis_sdk_node/src/sdk/__test__/identity.test.ts, jarvis_sdk_node/src/sdk/identity.ts
=> Token enrichment feature

jarvis_sdk_node/src/sdk/client/__test__/client.test.ts, jarvis_sdk_node/src/sdk/client/client.ts
=> Fix retrieving multiple messages from 1 grpc request

jarvis_sdk_node/package.json, jarvis_sdk_node/src/sdk/__test__/config.test.ts, jarvis_sdk_node/src/sdk/config.ts, jarvis_sdk_node/src/sdk/model/__test__/application_agent.test.ts, jarvis_sdk_node/src/sdk/model/__test__/application_agent_credential.test.ts, jarvis_sdk_node/src/sdk/model/application_agent.ts, jarvis_sdk_node/src/sdk/model/application_agent_credential.ts
=> Add crud + list operations for app agent and app agent credentials

.github/workflows/release.yaml
Adds metadata publisher github action.
=> ci: add metadata publisher github action

jarvis_sdk_node/src/sdk/client/client.ts
=> Fix interceptor when received message is null

.github/workflows/release.yaml
=> ci: remove clickup release step

jarvis_sdk_node/src/sdk/__test__/config/oauth2_client.test.ts, jarvis_sdk_node/src/sdk/config.ts, jarvis_sdk_node/src/sdk/model/config/__test__/factory.test.ts, jarvis_sdk_node/src/sdk/model/config/factory.ts, jarvis_sdk_node/src/sdk/model/config/oauth2Client/__test__/factory.test.ts, jarvis_sdk_node/src/sdk/model/config/oauth2Client/__test__/oauth2_client.test.ts, jarvis_sdk_node/src/sdk/model/config/oauth2Client/factory.ts, jarvis_sdk_node/src/sdk/model/config/oauth2Client/oauth2_client.ts
=> Add support for OAuth2 client management

.github/workflows/release.yaml
=> ci: switch to identity workload provider

commitlint.config.js
=> ci: relax the commitlint rules for subject case

.github/workflows/codeql-analysis.yml
=> ci: add codeql analysis workflow

jarvis_sdk_node/src/sdk/__test__/identity/identity.test.ts, jarvis_sdk_node/src/sdk/__test__/identity/is_authorized.test.ts, jarvis_sdk_node/src/sdk/identity.ts, jarvis_sdk_node/src/sdk/model/__test__/authorization_decisions.test.ts, jarvis_sdk_node/src/sdk/model/__test__/digitaltwin.test.ts, jarvis_sdk_node/src/sdk/model/__test__/property.test.ts, jarvis_sdk_node/src/sdk/model/authorization_decisions.ts, jarvis_sdk_node/src/sdk/model/digitaltwin.ts, jarvis_sdk_node/src/sdk/model/property.ts, jarvis_sdk_node/src/sdk/utils/utils.ts
=> Add isAuthorized API

jarvis_sdk_node/README.md, jarvis_sdk_node/src/examples/emailcfg.ts
=> Update readme file

jarvis_sdk_node/src/sdk/__test__/config/service_account.test.ts, jarvis_sdk_node/src/sdk/config.ts, jarvis_sdk_node/src/sdk/model/config/__test__/service_account.test.ts, jarvis_sdk_node/src/sdk/model/config/service_account.ts
=> Support the service accounts configuration

jarvis_sdk_node/src/sdk/__test__/config/permissions.test.ts, jarvis_sdk_node/src/sdk/config.ts, jarvis_sdk_node/src/sdk/model/config/__test__/permissions.test.ts, jarvis_sdk_node/src/sdk/model/config/index.ts, jarvis_sdk_node/src/sdk/model/config/permissions.ts
=> Support for permissions configuration

jarvis_sdk_node/src/grpc/indykite/config/v1beta1/model.ts, jarvis_sdk_node/src/sdk/__test__/authflow_config.test.ts, jarvis_sdk_node/src/sdk/model/config/authflow/factory.ts, jarvis_sdk_node/src/sdk/model/config/authflow/flow.ts
=> Update proto files

jarvis_sdk_node/src/sdk/__test__/config/service_account_credential.test.ts, jarvis_sdk_node/src/sdk/config.ts, jarvis_sdk_node/src/sdk/model/config/__test__/service_account_credential.test.ts, jarvis_sdk_node/src/sdk/model/config/index.ts, jarvis_sdk_node/src/sdk/model/config/service_account_credential.ts
=> Allow to configure service account credentials

jarvis_sdk_node/src/sdk/__test__/identity/password_credential.test.ts, jarvis_sdk_node/src/sdk/identity.ts
=> Allow to configure password credentials (not implemented on backend yet)

jarvis_sdk_node/src/sdk/__test__/identity/identity.test.ts, jarvis_sdk_node/src/sdk/identity.ts
=> Add list digital twins function

jarvis_sdk_node/src/sdk/__test__/identity/session_introspect.test.ts, jarvis_sdk_node/src/sdk/identity.ts, jarvis_sdk_node/src/sdk/utils/utils.ts
=> Add support for session introspection

jarvis_sdk_node/src/sdk/__test__/config/ingest_mapping.test.ts, jarvis_sdk_node/src/sdk/config.ts, jarvis_sdk_node/src/sdk/model/config/__test__/factory.test.ts, jarvis_sdk_node/src/sdk/model/config/factory.ts, jarvis_sdk_node/src/sdk/model/config/index.ts, jarvis_sdk_node/src/sdk/model/config/ingest_mapping/__test__/factory.test.ts, jarvis_sdk_node/src/sdk/model/config/ingest_mapping/__test__/ingest_mapping.test.ts, jarvis_sdk_node/src/sdk/model/config/ingest_mapping/factory.ts, jarvis_sdk_node/src/sdk/model/config/ingest_mapping/index.ts, jarvis_sdk_node/src/sdk/model/config/ingest_mapping/ingest_mapping.ts, jarvis_sdk_node/src/sdk/model/config/ingest_mapping/ingest_mapping_entity.ts
=> Add ingest mapping configuration

jarvis_sdk_node/package.json
=> Fix URLs in package.json

renovate.json
=> ci: change renovate to create single pr

renovate.json
=> Update node version used in renovate

indykite_sdk_node/package-lock.json
=> Repair package

indykite_sdk_node/src/sdk/http.ts, indykite_sdk_node/src/sdk/utils/token_source/token.ts, indykite_sdk_node/src/sdk/utils/token_source/token_source.ts
=> Code documentation

.github/workflows/release.yaml
=> ci: remove metadata publisher

indykite_sdk_node/src/sdk/authorization.ts
[ENG-395](https://indykite.atlassian.net/browse/ENG-395)
[ENG-395]: https://indykite.atlassian.net/browse/ENG-395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add method docs

.github/CODEOWNERS, indykite_sdk_node/src/sdk/__test__/authorization/what_authorized.test.ts, indykite_sdk_node/src/sdk/authorization.ts
[ENG-395](https://indykite.atlassian.net/browse/ENG-395)
[ENG-395]: https://indykite.atlassian.net/browse/ENG-395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add whatAuthorized method to the Authorization client 

indykite_sdk_node/package-lock.json, indykite_sdk_node/package.json
=> Revert rimraf version

.github/workflows/codeql-analysis.yml, .github/workflows/release.yaml, .github/workflows/tests.yaml
To address a rimraf being unsupported on node12
https://github.com/isaacs/rimraf/issues/265
=> build: bump node version to 14.x

indykite_sdk_node/src/sdk/__test__/authorization/who_authorized.test.ts, indykite_sdk_node/src/sdk/authorization.ts
[ENG-661](https://indykite.atlassian.net/browse/ENG-661)
[ENG-661]: https://indykite.atlassian.net/browse/ENG-661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add AuthorizationClient.whoAuthorized method

indykite_sdk_node/src/sdk/__test__/config/application_credential.test.ts, indykite_sdk_node/src/sdk/config.ts
[ENG-710](https://indykite.atlassian.net/browse/ENG-710)
[ENG-710]: https://indykite.atlassian.net/browse/ENG-710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Create one method for application with credentials creation

indykite_sdk_node/src/sdk/__test__/config/service_account.test.ts, indykite_sdk_node/src/sdk/config.ts
=> etag fix in delete service account function

indykite_sdk_node/src/grpc/indykite/authorization/v1beta1/authorization_service.ts, indykite_sdk_node/src/grpc/indykite/authorization/v1beta1/model.ts, indykite_sdk_node/src/sdk/__test__/authorization/is_authorized.test.ts, indykite_sdk_node/src/sdk/__test__/authorization/what_authorized.test.ts, indykite_sdk_node/src/sdk/__test__/authorization/who_authorized.test.ts, indykite_sdk_node/src/sdk/authorization.ts
[ENG-729](https://indykite.atlassian.net/browse/ENG-729)
[ENG-729]: https://indykite.atlassian.net/browse/ENG-729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Authorization options + policy tags support

indykite_sdk_node/src/sdk/__test__/identity/get_digital_twin_by_property.test.ts, indykite_sdk_node/src/sdk/identity.ts
[ENG-119](https://indykite.atlassian.net/browse/ENG-119)
[ENG-119]: https://indykite.atlassian.net/browse/ENG-119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Get DigitalTwin by a property

.github/workflows/generate-docs.yaml
=> chore: add workflow to generate documentation

.github/workflows/generate-docs.yaml
=> chore: rename branch in workflow

.github/workflows/generate-docs.yaml, .github/workflows/release-notes.yaml
=> chore: update PAT token name in workflows

indykite_sdk_node/src/grpc/indykite/config/v1beta1/config_management_api.ts
=> chore: update grpc

indykite_sdk_node/package-lock.json, indykite_sdk_node/package.json, indykite_sdk_node/scripts/fixApiDocLinks.ts, indykite_sdk_node/src/index.ts, indykite_sdk_node/src/sdk/__test__/identity_v2/client.test.ts, indykite_sdk_node/src/sdk/__test__/identity_v2/consent_challenge_and_verifier.test.ts, indykite_sdk_node/src/sdk/__test__/identity_v2/consents.test.ts, indykite_sdk_node/src/sdk/__test__/identity_v2/delete_digital_twin.test.ts, indykite_sdk_node/src/sdk/__test__/identity_v2/digital_twin_registration.test.ts, indykite_sdk_node/src/sdk/__test__/identity_v2/email_verification.test.ts, indykite_sdk_node/src/sdk/__test__/identity_v2/enrich-token.test.ts, indykite_sdk_node/src/sdk/__test__/identity_v2/get_digital_twin.test.ts, indykite_sdk_node/src/sdk/__test__/identity_v2/import_digital_twin.test.ts, indykite_sdk_node/src/sdk/__test__/identity_v2/introspect_token.test.ts, indykite_sdk_node/src/sdk/__test__/identity_v2/invitation.test.ts, indykite_sdk_node/src/sdk/__test__/identity_v2/password.test.ts, indykite_sdk_node/src/sdk/__test__/identity_v2/patch_digital_twin.test.ts, indykite_sdk_node/src/sdk/identity_v2.ts
=> Align Identity client API with Go SDK

indykite_sdk_node/src/examples/ingest.ts, indykite_sdk_node/src/grpc/indykite/config/v1beta1/model.ts, indykite_sdk_node/src/sdk/__test__/ingest_v2/ingest.test.ts, indykite_sdk_node/src/sdk/__test__/ingest_v2/new_client.test.ts, indykite_sdk_node/src/sdk/error.ts, indykite_sdk_node/src/sdk/ingest.ts, indykite_sdk_node/src/sdk/ingest_v2.ts
Update ingest client to version 2 with correct method definitions.
=> #ENG-1508 Update ingest client

README.md, indykite_sdk_node/config_example.json, indykite_sdk_node/src/grpc/indykite/config/v1beta1/model.ts, indykite_sdk_node/src/sdk/model/__test__/consent_challenge.test.ts, indykite_sdk_node/src/sdk/model/config/oauth2_client/__test__/oauth2_client.test.ts, indykite_sdk_node/src/sdk/utils/__test__/application_credential.test.ts, indykite_sdk_node/src/sdk/utils/__test__/service_account_credential.test.ts, indykite_sdk_node/src/sdk/utils/__test__/utils.test.ts, indykite_sdk_node/src/sdk/utils/application_credential.ts, indykite_sdk_node/src/sdk/utils/credential.ts, indykite_sdk_node/src/sdk/utils/service_account_credential.ts, indykite_sdk_node/src/sdk/utils/test_utils.ts, indykite_sdk_node/src/sdk/utils/utils.ts
Based on requirements of #ENG-1478 added tokenLifetime to credentials
=> #ENG-1478 added tokenLifetime to credentials

indykite_sdk_node/src/grpc/indykite/config/v1beta1/config_management_api.grpc-client.ts, indykite_sdk_node/src/grpc/indykite/config/v1beta1/config_management_api.ts, indykite_sdk_node/src/grpc/indykite/config/v1beta1/model.ts, indykite_sdk_node/src/sdk/__test__/config/authorization_policy.test.ts, indykite_sdk_node/src/sdk/__test__/config/oauth2_client.test.ts, indykite_sdk_node/src/sdk/__test__/config/oauth2_provider.test.ts, indykite_sdk_node/src/sdk/__test__/config/webauthn_provider.test.ts, indykite_sdk_node/src/sdk/__test__/config_v2/config_node.test.ts, indykite_sdk_node/src/sdk/__test__/config_v2/oauth2_provider.test.ts, indykite_sdk_node/src/sdk/config_v2.ts, indykite_sdk_node/src/sdk/model/config/__test__/factory.test.ts, indykite_sdk_node/src/sdk/model/config/__test__/oauth2_provider_config.test.ts, indykite_sdk_node/src/sdk/model/config/oauth2_provider_config.ts
#ENG-1752 added listConfigNodeVersions method
Update the gPRC model
Updated unit tests
=> feat: add listConfigNodeVersions method

indykite_sdk_node/src/grpc/indykite/authorization/v1beta1/model.ts, indykite_sdk_node/src/grpc/indykite/ingest/v1beta2/model.ts, indykite_sdk_node/src/grpc/indykite/knowledge/v1beta1/identity_knowledge_api.ts, indykite_sdk_node/src/grpc/indykite/knowledge/v1beta1/model.ts, indykite_sdk_node/src/sdk/__test__/authorization_v2/is_authorized.test.ts, indykite_sdk_node/src/sdk/__test__/authorization_v2/what_authorized.test.ts, indykite_sdk_node/src/sdk/__test__/knowledge/knowledge.test.ts, indykite_sdk_node/src/sdk/authorization_v2.ts
[ENG-1826](https://indykite.atlassian.net/browse/ENG-1826)
The subject proto message in the authorization service has changed.
[ENG-1826]: https://indykite.atlassian.net/browse/ENG-1826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: update subject type for authz

indykite_sdk_node/src/index.ts
added missing export of the IdentityKnowledgeClient
=> exporting new IdentityKnowledgeClient

indykite_sdk_node/src/grpc/indykite/ingest/v1beta2/model.ts, indykite_sdk_node/src/sdk/__test__/ingest/ingest.test.ts, indykite_sdk_node/src/sdk/__test__/ingest_v2/ingest.test.ts, indykite_sdk_node/src/sdk/ingest.ts
=> feat: add optional id to digital twin ingest

indykite_sdk_node/src/examples/ingest.ts
=> doc: add optional id to ingest example

codecov.yaml, indykite_sdk_node/src/sdk/knowledge.ts
Eng 2264 delete utility function identityknowledge
=> Eng 2264 delete utility function identityknowledge

.github/workflows/generate-docs.yaml, README.md, indykite_sdk_node/typedoc.json
=> fix: repair doc-generate
